language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

matrix:
  include:
    - os: linux
      dist: xenial
      script:
        - CC=gcc-7 && CXX=g++-7
        - mkdir build && cd build
        - cmake ../ -DCMAKE_INSTALL_PREFIX=./installed
        - make -j2 && make install
        - cd installed/bin
        - ./test
    - os: windows
      env:
        - CMAKE_PATH="/c/Program Files/CMake/bin"
      script:
        - mkdir build && cd build
        - cmake ../ -DCMAKE_INSTALL_PREFIX=./installed
        - cmake --build .
        - cmake --build . --target INSTALL
        - cd installed
        - ./test.exe
